package gui;

import engine.GraphDrawer;
import engine.GraphMaker;
import engine.SVGParser;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.net.URI;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebView;
import javax.swing.GroupLayout.Group;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author Albert - 2014730007
 */
public class ApplicationGUI extends javax.swing.JFrame {
    private JFileChooser fileChooser;
    private SVGParser svgParser;
    private GraphMaker graphMaker;
    private GraphDrawer graphDrawer;
    WebView webViewInput;
    WebView webViewOutput;
    
    /**
     * Creates new form ApplicationGUI
     */
    public ApplicationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane3 = new javax.swing.JEditorPane();
        navPanel = new javax.swing.JPanel();
        homeNav = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        generateProblemNav = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        homeContent = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelPetunjuk = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaPetunjuk = new javax.swing.JTextArea();
        generateProblemContent = new javax.swing.JPanel();
        browseButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputPane = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        outputPane = new javax.swing.JEditorPane();

        jScrollPane4.setViewportView(jEditorPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        navPanel.setBackground(new java.awt.Color(54, 33, 89));
        navPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeNav.setBackground(new java.awt.Color(85, 65, 118));
        homeNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeNavMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Home_15px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Home");

        javax.swing.GroupLayout homeNavLayout = new javax.swing.GroupLayout(homeNav);
        homeNav.setLayout(homeNavLayout);
        homeNavLayout.setHorizontalGroup(
            homeNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeNavLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        homeNavLayout.setVerticalGroup(
            homeNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeNavLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(homeNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        navPanel.add(homeNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 50));

        generateProblemNav.setBackground(new java.awt.Color(64, 43, 100));
        generateProblemNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generateProblemNavMousePressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Refresh_15px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Generate Problem");

        javax.swing.GroupLayout generateProblemNavLayout = new javax.swing.GroupLayout(generateProblemNav);
        generateProblemNav.setLayout(generateProblemNavLayout);
        generateProblemNavLayout.setHorizontalGroup(
            generateProblemNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateProblemNavLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        generateProblemNavLayout.setVerticalGroup(
            generateProblemNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateProblemNavLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(generateProblemNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        navPanel.add(generateProblemNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 50));

        contentPanel.setLayout(new java.awt.CardLayout());

        homeContent.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(110, 89, 222));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Connecting Dot Problem Generator");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(400, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        labelPetunjuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPetunjuk.setText("Petunjuk:");

        textAreaPetunjuk.setEditable(false);
        textAreaPetunjuk.setColumns(20);
        textAreaPetunjuk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaPetunjuk.setLineWrap(true);
        textAreaPetunjuk.setRows(5);
        textAreaPetunjuk.setText("Program ini digunakan untuk membuat soal permainan menghubungkan titik. Masukan program berupa file SVG dan keluaran program berupa file HTML. Pembuatan soal dapat dilakukan pada panel Generate Problem. Klik Generate Problem pada navigasi untuk berpindah ke panel Generate Problem.\n\nKlik tombol Browse pada panel Generate Problem untuk menentukan file masukan. Setelah itu, program akan meminta lokasi penyimpanan dan nama file yang akan disimpan. Pratinjau file masukan dan keluaran akan ditampilkan pada panel Generate Problem.");
        textAreaPetunjuk.setToolTipText(null);
        textAreaPetunjuk.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textAreaPetunjuk);

        javax.swing.GroupLayout homeContentLayout = new javax.swing.GroupLayout(homeContent);
        homeContent.setLayout(homeContentLayout);
        homeContentLayout.setHorizontalGroup(
            homeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homeContentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(homeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPetunjuk)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeContentLayout.setVerticalGroup(
            homeContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeContentLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(labelPetunjuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        contentPanel.add(homeContent, "card2");

        generateProblemContent.setBackground(new java.awt.Color(255, 255, 255));

        browseButton.setBackground(new java.awt.Color(54, 33, 89));
        browseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                browseButtonMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Open_20px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Browse");

        javax.swing.GroupLayout browseButtonLayout = new javax.swing.GroupLayout(browseButton);
        browseButton.setLayout(browseButtonLayout);
        browseButtonLayout.setHorizontalGroup(
            browseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(browseButtonLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(46, 46, 46))
        );
        browseButtonLayout.setVerticalGroup(
            browseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        inputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputLabel.setText("Input:");

        outputLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        outputLabel.setText("Output:");

        inputPane.setEditable(false);
        jScrollPane1.setViewportView(inputPane);

        outputPane.setEditable(false);
        jScrollPane5.setViewportView(outputPane);

        javax.swing.GroupLayout generateProblemContentLayout = new javax.swing.GroupLayout(generateProblemContent);
        generateProblemContent.setLayout(generateProblemContentLayout);
        generateProblemContentLayout.setHorizontalGroup(
            generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateProblemContentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputLabel))
                .addGap(18, 18, 18)
                .addGroup(generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generateProblemContentLayout.createSequentialGroup()
                        .addComponent(outputLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generateProblemContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );
        generateProblemContentLayout.setVerticalGroup(
            generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateProblemContentLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outputLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generateProblemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        contentPanel.add(generateProblemContent, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNavMousePressed
        setColor(homeNav);
        resetColor(generateProblemNav);
        
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(homeContent);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_homeNavMousePressed

    private void generateProblemNavMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateProblemNavMousePressed
        setColor(generateProblemNav);
        resetColor(homeNav);
        
        contentPanel.removeAll();
        contentPanel.repaint();
        contentPanel.revalidate();
        
        contentPanel.add(generateProblemContent);
        contentPanel.repaint();
        contentPanel.revalidate();
    }//GEN-LAST:event_generateProblemNavMousePressed

    private void browseButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_browseButtonMousePressed
        fileChooser = new JFileChooser(new File("C:/"));
        fileChooser.setFileFilter(new FileNameExtensionFilter("SVG files", "svg"));
        fileChooser.setDialogTitle("Choose SVG File");
        int feedback = fileChooser.showOpenDialog(this);
        final String inputURI = fileChooser.getSelectedFile().getAbsolutePath();
        if(feedback == JFileChooser.APPROVE_OPTION){
            svgParser = new SVGParser(fileChooser.getSelectedFile());
            svgParser.parseFile();
            graphMaker = new GraphMaker(svgParser.getElements());
            fileChooser = new JFileChooser(new File("C:/"));
            fileChooser.setFileFilter(new FileNameExtensionFilter("SVG files", "svg"));
            fileChooser.setDialogTitle("Save Converted File");
            feedback = fileChooser.showSaveDialog(this);
            final String outputURI = fileChooser.getSelectedFile().getAbsolutePath();
            if(feedback == JFileChooser.APPROVE_OPTION){
                try{
                    graphDrawer = new GraphDrawer(graphMaker.getResult(), svgParser.getUnprocessedElements(), fileChooser.getSelectedFile(), svgParser.getSvgWidth(), svgParser.getSvgHeight());
                    graphDrawer.draw();
                    
                    JFXPanel jfxInput = new JFXPanel();
                    JFXPanel jfxOutput = new JFXPanel();
                    inputPane.add(jfxInput);
                    outputPane.add(jfxOutput);
                    Platform.runLater(new Runnable() {
                        @Override
                        public void run(){
                            if(webViewInput==null){
                                webViewInput = new WebView();
                                jfxInput.setScene(new Scene(webViewInput));
                            }
                            webViewInput.getEngine().load("file:///"+inputURI);
                            jfxInput.setVisible(true);
                            jfxInput.setBounds(0, 0, inputPane.getWidth(), inputPane.getHeight());

                            if(webViewOutput==null){
                                webViewOutput = new WebView();
                                jfxOutput.setScene(new Scene(webViewOutput));
                            }
                            webViewOutput.getEngine().load("file:///"+outputURI);
                            jfxOutput.setVisible(true);
                            jfxOutput.setBounds(0, 0, outputPane.getWidth(), outputPane.getHeight());
                        }
                    });
                    
                    JOptionPane.showMessageDialog(this, "Berhasil Membuat Soal");
                }
                catch(Exception e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_browseButtonMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(85, 65, 118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(64, 43, 100));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ApplicationGUI gui = new ApplicationGUI();
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel browseButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel generateProblemContent;
    private javax.swing.JPanel generateProblemNav;
    private javax.swing.JPanel homeContent;
    private javax.swing.JPanel homeNav;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JEditorPane inputPane;
    private javax.swing.JEditorPane jEditorPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelPetunjuk;
    private javax.swing.JPanel navPanel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JEditorPane outputPane;
    private javax.swing.JTextArea textAreaPetunjuk;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
